name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: build.bat

      - name: Build (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Tests (Windows)
        if: runner.os == 'Windows'
        run: test.bat

      - name: Tests (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          chmod +x test.sh
          ./test.sh
